pivio:
  build: .
  ports:
   - "9123:9123"
  links:
   - elasticsearch

elasticsearch:
  image: elasticsearch:2.4.6
  command: ["/bin/sh", "-c", "plugin install delete-by-query && gosu elasticsearch elasticsearch"]
